# Generated by Django 5.2.14 on 2026-07-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_add_is_visible_to_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
