# Generated by Django 5.2.14 on 2026-06-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('MANAGER', 'Manager'), ('STAFF', 'Staff'), ('CUSTOMER', 'Customer')], default='STAFF', max_length=30),
        ),
    ]
