# Generated by Django 5.2.14 on 2026-08-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_restore_order_vnpay_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vnpay_paid_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vnpay_txn_ref',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'COD'), ('bank_transfer', 'Chuyển khoản')], default='cod', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán')], default='unpaid', max_length=20),
        ),
    ]
