# Generated by Django 5.2.14 on 2026-07-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_add_is_visible_to_blog_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=30),
        ),
    ]
