# Generated by Django 5.2.14 on 2026-05-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_suggested',
            field=models.BooleanField(default=False),
        ),
    ]
