# Generated by Django 5.2.14 on 2026-06-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_suggested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='null = chưa set, 0 = thanh lý miễn phí, >0 = giá bán', max_digits=15, null=True),
        ),
    ]
