# Generated by Django 5.2.15 on 2026-07-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_is_visible_to_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_suggested',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='null = chưa set, 0 = thanh lý miễn phí, >0 = giá bán', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending_price', 'Pending Price'), ('in_stock', 'In Stock'), ('sold', 'Sold'), ('cancelled', 'Cancelled')], db_index=True, default='pending_price', max_length=30),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
