# Generated by Django 5.2.15 on 2026-07-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='telegram',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='zalo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
